services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    image: "postgres:17"
    env_file: ".env"
    volumes:
      - dbdata:/data

volumes:
  dbdata:
