services:
  web:
    build: .
    command: go run main.go
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - appdata:/data
    develop:
      watch:
        - action: rebuild
          path: ./
          target: /app
  db:
    image: "postgres:17"
    env_file: ".env"
    volumes:
      - dbdata:/data

volumes:
  dbdata:
  appdata:
