CREATE TABLE IF NOT EXISTS users (
Id SERIAL PRIMARY KEY,
	Name TEXT NOT NULL,
	Email TEXT UNIQUE,
	Phone TEXT,
	Password VARCHAR(255),
	Birthday DATE NOT NULL,
	CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
	CHECK ((Email IS NOT NULL) OR (Phone IS NOT NULL))
);

CREATE TYPE LEVEL as ENUM ('read', 'write', 'admin');

CREATE TABLE IF NOT EXISTS role_types (
Id SERIAL PRIMARY KEY,
	Title TEXT NOT NULL,
	CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
	AccessLevel LEVEL NOT NULL DEFAULT 'read'
);

CREATE TABLE IF NOT EXISTS roles (
Id SERIAL PRIMARY KEY,
	UserId INTEGER NOT NULL REFERENCES users(Id),
	RoleTypeId INTEGER NOT NULL REFERENCES role_types(Id),
	CreatedAt TIMESTAMP NOT NULL DEFAULT NOW()
);
