// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package internal

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE Id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const deleteRoleType = `-- name: DeleteRoleType :exec
DELETE FROM role_types WHERE Id = $1
`

func (q *Queries) DeleteRoleType(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRoleType, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE Id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getRoleById = `-- name: GetRoleById :one
SELECT id, userid, roletypeid, createdat FROM roles WHERE Id = $1 LIMIT 1
`

func (q *Queries) GetRoleById(ctx context.Context, id int32) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleById, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Roletypeid,
		&i.Createdat,
	)
	return i, err
}

const getRoleTypeById = `-- name: GetRoleTypeById :one
SELECT id, title, createdat, accesslevel FROM role_types WHERE Id = $1 LIMIT 1
`

func (q *Queries) GetRoleTypeById(ctx context.Context, id int32) (RoleType, error) {
	row := q.db.QueryRow(ctx, getRoleTypeById, id)
	var i RoleType
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Createdat,
		&i.Accesslevel,
	)
	return i, err
}

const getSessionById = `-- name: GetSessionById :one
SELECT id, userid, createdat, lastseenat, expiresat, ipaddress, useragent, isactive FROM sessions
WHERE Id = $1
AND IsActive = TRUE
LIMIT 1
`

func (q *Queries) GetSessionById(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Createdat,
		&i.Lastseenat,
		&i.Expiresat,
		&i.Ipaddress,
		&i.Useragent,
		&i.Isactive,
	)
	return i, err
}

const getSessionsForUser = `-- name: GetSessionsForUser :many
SELECT id, userid, createdat, lastseenat, expiresat, ipaddress, useragent, isactive FROM sessions
WHERE UserId = $1
  AND IsActive = TRUE
  AND ExpiresAt > NOW()
`

func (q *Queries) GetSessionsForUser(ctx context.Context, userid int32) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessionsForUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Userid,
			&i.Createdat,
			&i.Lastseenat,
			&i.Expiresat,
			&i.Ipaddress,
			&i.Useragent,
			&i.Isactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, phone, password, birthday, createdat FROM users WHERE Email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Birthday,
		&i.Createdat,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, email, phone, password, birthday, createdat FROM users WHERE Id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Birthday,
		&i.Createdat,
	)
	return i, err
}

const getUserStats = `-- name: GetUserStats :one
SELECT
    COUNT(*) AS current_count,
    SUM(CASE WHEN CreatedAt <= NOW() - INTERVAL '1 month' THEN 1 ELSE 0 END) AS count_a_month_ago
FROM users
`

type GetUserStatsRow struct {
	CurrentCount   int64
	CountAMonthAgo int64
}

func (q *Queries) GetUserStats(ctx context.Context) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats)
	var i GetUserStatsRow
	err := row.Scan(&i.CurrentCount, &i.CountAMonthAgo)
	return i, err
}

const insertRole = `-- name: InsertRole :one
INSERT INTO roles (UserId, RoleTypeId) VALUES ($1, $2) RETURNING id, userid, roletypeid, createdat
`

type InsertRoleParams struct {
	Userid     int32
	Roletypeid int32
}

func (q *Queries) InsertRole(ctx context.Context, arg InsertRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, insertRole, arg.Userid, arg.Roletypeid)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Roletypeid,
		&i.Createdat,
	)
	return i, err
}

const insertRoleType = `-- name: InsertRoleType :one
INSERT INTO role_types (Title, AccessLevel) VALUES ($1, $2) RETURNING id, title, createdat, accesslevel
`

type InsertRoleTypeParams struct {
	Title       string
	Accesslevel Level
}

func (q *Queries) InsertRoleType(ctx context.Context, arg InsertRoleTypeParams) (RoleType, error) {
	row := q.db.QueryRow(ctx, insertRoleType, arg.Title, arg.Accesslevel)
	var i RoleType
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Createdat,
		&i.Accesslevel,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (Name, Email, Phone, Birthday) VALUES ($1,$2,$3,$4) RETURNING id, name, email, phone, password, birthday, createdat
`

type InsertUserParams struct {
	Name     string
	Email    string
	Phone    pgtype.Text
	Birthday pgtype.Date
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Birthday,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Birthday,
		&i.Createdat,
	)
	return i, err
}

const invalidateSession = `-- name: InvalidateSession :exec
UPDATE sessions SET IsActive = FALSE WHERE Id = $1
`

func (q *Queries) InvalidateSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, invalidateSession, id)
	return err
}

const listRoleTypes = `-- name: ListRoleTypes :many
SELECT id, title, createdat, accesslevel FROM role_types
`

func (q *Queries) ListRoleTypes(ctx context.Context) ([]RoleType, error) {
	rows, err := q.db.Query(ctx, listRoleTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleType
	for rows.Next() {
		var i RoleType
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Createdat,
			&i.Accesslevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, userid, roletypeid, createdat FROM roles
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Userid,
			&i.Roletypeid,
			&i.Createdat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, phone, password, birthday, createdat FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Password,
			&i.Birthday,
			&i.Createdat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newSession = `-- name: NewSession :one
INSERT INTO sessions (UserId, ExpiresAt, IpAddress, UserAgent) VALUES ($1, $2, $3, $4) RETURNING id, userid, createdat, lastseenat, expiresat, ipaddress, useragent, isactive
`

type NewSessionParams struct {
	Userid    int32
	Expiresat pgtype.Timestamptz
	Ipaddress *netip.Addr
	Useragent pgtype.Text
}

func (q *Queries) NewSession(ctx context.Context, arg NewSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, newSession,
		arg.Userid,
		arg.Expiresat,
		arg.Ipaddress,
		arg.Useragent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Createdat,
		&i.Lastseenat,
		&i.Expiresat,
		&i.Ipaddress,
		&i.Useragent,
		&i.Isactive,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, name, email, phone, password, birthday, createdat FROM users WHERE Name ILIKE $1 OR Email ILIKE $1 OR Phone ILIKE 1
`

func (q *Queries) SearchUsers(ctx context.Context, name string) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Password,
			&i.Birthday,
			&i.Createdat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionLastActive = `-- name: SetSessionLastActive :one
UPDATE sessions SET LastSeenAt = NOW() WHERE Id = $1 AND IsActive = TRUE RETURNING id, userid, createdat, lastseenat, expiresat, ipaddress, useragent, isactive
`

func (q *Queries) SetSessionLastActive(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, setSessionLastActive, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Createdat,
		&i.Lastseenat,
		&i.Expiresat,
		&i.Ipaddress,
		&i.Useragent,
		&i.Isactive,
	)
	return i, err
}

const updateUserPass = `-- name: UpdateUserPass :one
UPDATE users SET Password=$2 WHERE Id = $1 RETURNING id, name, email, phone, password, birthday, createdat
`

type UpdateUserPassParams struct {
	ID       int32
	Password pgtype.Text
}

func (q *Queries) UpdateUserPass(ctx context.Context, arg UpdateUserPassParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPass, arg.ID, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Birthday,
		&i.Createdat,
	)
	return i, err
}
